/* Auto-generated by genmsg_cpp for file /home/rosbuild/hudson/workspace/doc-electric-p2os/doc_stacks/2013-03-01_16-19-23.450784/p2os/p2os_driver/msg/PTZState.msg */
#ifndef P2OS_DRIVER_MESSAGE_PTZSTATE_H
#define P2OS_DRIVER_MESSAGE_PTZSTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace p2os_driver
{
template <class ContainerAllocator>
struct PTZState_ {
  typedef PTZState_<ContainerAllocator> Type;

  PTZState_()
  : pan(0)
  , tilt(0)
  , zoom(0)
  , relative(false)
  {
  }

  PTZState_(const ContainerAllocator& _alloc)
  : pan(0)
  , tilt(0)
  , zoom(0)
  , relative(false)
  {
  }

  typedef int32_t _pan_type;
  int32_t pan;

  typedef int32_t _tilt_type;
  int32_t tilt;

  typedef int32_t _zoom_type;
  int32_t zoom;

  typedef uint8_t _relative_type;
  uint8_t relative;


private:
  static const char* __s_getDataType_() { return "p2os_driver/PTZState"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "1f71ce2a42b32376ea869eb051358045"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int32 pan\n\
int32 tilt\n\
int32 zoom\n\
bool relative\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, pan);
    ros::serialization::serialize(stream, tilt);
    ros::serialization::serialize(stream, zoom);
    ros::serialization::serialize(stream, relative);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, pan);
    ros::serialization::deserialize(stream, tilt);
    ros::serialization::deserialize(stream, zoom);
    ros::serialization::deserialize(stream, relative);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(pan);
    size += ros::serialization::serializationLength(tilt);
    size += ros::serialization::serializationLength(zoom);
    size += ros::serialization::serializationLength(relative);
    return size;
  }

  typedef boost::shared_ptr< ::p2os_driver::PTZState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::p2os_driver::PTZState_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PTZState
typedef  ::p2os_driver::PTZState_<std::allocator<void> > PTZState;

typedef boost::shared_ptr< ::p2os_driver::PTZState> PTZStatePtr;
typedef boost::shared_ptr< ::p2os_driver::PTZState const> PTZStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::p2os_driver::PTZState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::p2os_driver::PTZState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace p2os_driver

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::p2os_driver::PTZState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::p2os_driver::PTZState_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::p2os_driver::PTZState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1f71ce2a42b32376ea869eb051358045";
  }

  static const char* value(const  ::p2os_driver::PTZState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1f71ce2a42b32376ULL;
  static const uint64_t static_value2 = 0xea869eb051358045ULL;
};

template<class ContainerAllocator>
struct DataType< ::p2os_driver::PTZState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "p2os_driver/PTZState";
  }

  static const char* value(const  ::p2os_driver::PTZState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::p2os_driver::PTZState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 pan\n\
int32 tilt\n\
int32 zoom\n\
bool relative\n\
\n\
";
  }

  static const char* value(const  ::p2os_driver::PTZState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::p2os_driver::PTZState_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::p2os_driver::PTZState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.pan);
    stream.next(m.tilt);
    stream.next(m.zoom);
    stream.next(m.relative);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PTZState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::p2os_driver::PTZState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::p2os_driver::PTZState_<ContainerAllocator> & v) 
  {
    s << indent << "pan: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pan);
    s << indent << "tilt: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tilt);
    s << indent << "zoom: ";
    Printer<int32_t>::stream(s, indent + "  ", v.zoom);
    s << indent << "relative: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relative);
  }
};


} // namespace message_operations
} // namespace ros

#endif // P2OS_DRIVER_MESSAGE_PTZSTATE_H
