/* Auto-generated by genmsg_cpp for file /home/rosbuild/hudson/workspace/doc-electric-p2os/doc_stacks/2013-03-01_16-19-23.450784/p2os/p2os_driver/msg/SonarArray.msg */
#ifndef P2OS_DRIVER_MESSAGE_SONARARRAY_H
#define P2OS_DRIVER_MESSAGE_SONARARRAY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace p2os_driver
{
template <class ContainerAllocator>
struct SonarArray_ {
  typedef SonarArray_<ContainerAllocator> Type;

  SonarArray_()
  : header()
  , ranges_count(0)
  , ranges()
  {
  }

  SonarArray_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , ranges_count(0)
  , ranges(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int32_t _ranges_count_type;
  int32_t ranges_count;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _ranges_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  ranges;


  ROS_DEPRECATED uint32_t get_ranges_size() const { return (uint32_t)ranges.size(); }
  ROS_DEPRECATED void set_ranges_size(uint32_t size) { ranges.resize((size_t)size); }
  ROS_DEPRECATED void get_ranges_vec(std::vector<double, typename ContainerAllocator::template rebind<double>::other > & vec) const { vec = this->ranges; }
  ROS_DEPRECATED void set_ranges_vec(const std::vector<double, typename ContainerAllocator::template rebind<double>::other > & vec) { this->ranges = vec; }
private:
  static const char* __s_getDataType_() { return "p2os_driver/SonarArray"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "2984921c09aef26ad253c7629937a5bb"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
int32 ranges_count\n\
float64[] ranges\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, ranges_count);
    ros::serialization::serialize(stream, ranges);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, ranges_count);
    ros::serialization::deserialize(stream, ranges);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(ranges_count);
    size += ros::serialization::serializationLength(ranges);
    return size;
  }

  typedef boost::shared_ptr< ::p2os_driver::SonarArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::p2os_driver::SonarArray_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SonarArray
typedef  ::p2os_driver::SonarArray_<std::allocator<void> > SonarArray;

typedef boost::shared_ptr< ::p2os_driver::SonarArray> SonarArrayPtr;
typedef boost::shared_ptr< ::p2os_driver::SonarArray const> SonarArrayConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::p2os_driver::SonarArray_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::p2os_driver::SonarArray_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace p2os_driver

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::p2os_driver::SonarArray_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::p2os_driver::SonarArray_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::p2os_driver::SonarArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2984921c09aef26ad253c7629937a5bb";
  }

  static const char* value(const  ::p2os_driver::SonarArray_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2984921c09aef26aULL;
  static const uint64_t static_value2 = 0xd253c7629937a5bbULL;
};

template<class ContainerAllocator>
struct DataType< ::p2os_driver::SonarArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "p2os_driver/SonarArray";
  }

  static const char* value(const  ::p2os_driver::SonarArray_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::p2os_driver::SonarArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int32 ranges_count\n\
float64[] ranges\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::p2os_driver::SonarArray_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::p2os_driver::SonarArray_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::p2os_driver::SonarArray_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::p2os_driver::SonarArray_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.ranges_count);
    stream.next(m.ranges);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SonarArray_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::p2os_driver::SonarArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::p2os_driver::SonarArray_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ranges_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ranges_count);
    s << indent << "ranges[]" << std::endl;
    for (size_t i = 0; i < v.ranges.size(); ++i)
    {
      s << indent << "  ranges[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.ranges[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // P2OS_DRIVER_MESSAGE_SONARARRAY_H
